### ISSUE TITLE
Do I need to Import Assets first?

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [Lakifume/True-Randomization#11]
Oh nvm about Import Assets.. I got this:
![image](https://user-images.githubusercontent.com/10475153/163588139-09898b03-02cf-40bd-a1a3-18906dab2010.png)

But after click Generate, entering some random number and click New Seed or Confirm, it always crushes every time.
![crush](https://user-images.githubusercontent.com/10475153/163589372-0898160e-d02e-4d26-91cf-faef0438c481.gif)

**Comment by Lakifume** [comment]
Open the exe in a cmd, generate again and see if an error shows up on the command window.

**Comment by ParanoiaIsGreat** [comment]
After open it in Powershell, it suddenly works :) And now works fine even without it. 
Thanks a lot!
![image](https://user-images.githubusercontent.com/10475153/163597900-0309927a-1b88-4dc0-aeed-00ec0df532fa.png)

**Comment by Lakifume** [comment]
Huh, some weird computer jank I guess. Glad it works.
