### ISSUE TITLE
Door to nowhere?

### ISSUE THREAD

**Issue by MainMemory** [Lakifume/True-Randomization#14]
Using version 2.7.2 of the mod, in seed 2423152452, there is a door that does not seem to connect to another room, even though the map indicates that it should. Miriam will open the door and walk offscreen for several seconds, until she eventually stops, and I can then walk back through the open door.
My settings:
![image](https://user-images.githubusercontent.com/6082665/183353948-f309d0f0-6897-46e2-9209-e022ee1d5158.png)
The door in question:
![20220807165833_1](https://user-images.githubusercontent.com/6082665/183353994-f810a257-0589-4940-b82b-ef50432c5334.jpg)

**Comment by Lakifume** [comment]
Oh I see the issue, thanks for reporting.
