### ISSUE TITLE
Add enemy definable when making custom castle

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lakifume/True-Randomization#15]
So a simple way you could do this is use a spawn id so example bat would be spawn id 1 and set the grid per room which I am not sure how the rooms are sliced I heard this symphony of the night style 16 by 16 squares. Theoretcially you could grid rooms and allow users to define enemy spawns. I would assume it would start buggy but I am happy to help you test.

**Comment by P3rf3ctXZer0** [comment]
(thinking about you might be able to pull definable quickly through console debug) Then its just a matter of adding callbacks. This would slowly open the way to custom things as well but one black at a time. 🌠

**Comment by Lakifume** [comment]
You mean adding the option to edit room entities ? My map editor only focuses on facilitating the creation of custom room layouts for use with the randomizer. For an editor that allows changing each room's 3d environment use Giwayume's Godot program, you can access it by pressing the Credits button and clicking on the Github link below his name.

**Comment by P3rf3ctXZer0** [comment]
No I just want to play entities but I understand if that is too much I was just hoping for an all in one tool.
