### ISSUE TITLE
File Not Found Exception

### ISSUE THREAD

**Issue by Jces00** [Lakifume/True-Randomization#18]
¡Help Please! I have an issue with the randomizer 'E:\True.Randomization\Game\Core\Character\N3127\Material\MI_N3127_Eye.uasset' the file is not found and i can't create any seed. I don't know where it is or where it should be. It's the first time i use this tool.

**Comment by Lakifume** [comment]
Are you sure that you are on the latest version of Bloodstained (v1.4) ?
