### ISSUE TITLE
Bael has insane projectile speed

### ISSUE THREAD

**Issue by Akerback** [Lakifume/True-Randomization#19]
I had just gotten to the final boss in a randomizer run but Bael has very high projectile speed. This is the only run I've seen this happen and it's applying to all my save files regardless of their difficulty. I have a music replacement mod too and tried removing it, but no change in projectile speed. 

I tried these configurations:

Music mod + randomizer: Fast projectiles
Randomizer only: Fast projectiles
Music mod only: Normal projectiles
No mods: Normal projectiles

Seed: #7782630999
Randomizer Settings: 
![bild](https://user-images.githubusercontent.com/100067319/193243249-8ad70004-af06-4cb0-b8b9-134b2e211e21.png)

Spoiler log: 
[KeyLocation.txt](https://github.com/Lakifume/True-Randomization/files/9683086/KeyLocation.txt)

What's happening: https://user-images.githubusercontent.com/100067319/193242487-a9758e51-bbda-403a-9a0d-e7c8332cb016.mp4

**Comment by Lakifume** [comment]
Yeah this is an intended fix for Bael getting 0 pattern changes on the harder difficulties in vanilla, to prevent him from being by far the easiest boss in the game in hard mode. This change only gets applied if you select hard or nightmare though, choosing normal difficulty will keep his vanilla patterns.
