### ISSUE TITLE
[FREQ] Store value of output folder from one randomizer run to the next

### ISSUE THREAD

**Issue by SenseiLeRoof** [Lakifume/True-Randomization#2]
As title. Having to run down the mod folder every time is a hassle.

**Comment by Lakifume** [comment]
To fix this we would have to code this entire interface into the game itself. Not realistically happening sadly.
But at least over the course of this mod's progress the process has gotten much easier and much faster.

**Comment by SenseiLeRoof** [comment]
What? All you'd need is to make a config file for the randomizer!

**Comment by Lakifume** [comment]
Wait but there is a config, all of your settings and output path do get stored after closing the interface. So all you'd need to do to generate again with the same settings is open the interface and press the Generate button.

**Comment by SenseiLeRoof** [comment]
Every time I've opened it, the output path field has been empty and no options have been checked. Does the config get wiped between versions or does the UI simply not reflect the stored settings in the config?

**Comment by Lakifume** [comment]
The config does get reset after updating to a new version, but other than that it should store everything you've set between usages. Unless something like your antivirus is blocking the writing of config.json.

**Comment by SenseiLeRoof** [comment]
Okay, that would explain things. I've yet to run two randomizer sessions in the same version because I keep thinking "I'm gonna finish the run this time!" and... oh look, Binding of Isaac mods have updated...

Until I have a chance to determine for myself, safely closing.
