### ISSUE TITLE
Uncollectable Item in Valac Room

### ISSUE THREAD

**Issue by MainMemory** [Lakifume/True-Randomization#20]
It seems like if the chest in the upper left corner of Valac's room gets replaced with an HP/MP Max Up item, it ends up in the background and cannot be collected.
![image](https://user-images.githubusercontent.com/6082665/202519367-fbc7ac22-82d7-4158-8544-97efa9c542f3.png)

**Comment by Lakifume** [comment]
Ah yes I see the issue there, thanks for reporting
