### ISSUE TITLE
Questions about the new Starting Items text box

### ISSUE THREAD

**Issue by SenseiLeRoof** [Lakifume/True-Randomization#21]
What do you enter to start with:

1. Multiples of consumables (e.g. Potion x9)?
2. "Coin" items (e.g. Dawn Blade level 2)?
3. White versions of yellow shards?

**Comment by Lakifume** [comment]
You can refer to the files under Data>Translation for more specific item names (the second row in each JSON). As for quantity that is automatically assigned based on the item types you input, for instance starting with potions will give you 3 of them, starting with bullets 30 of them...
