### ISSUE TITLE
Feature: Uncapped Stat Randomization

### ISSUE THREAD

**Issue by MainMemory** [Lakifume/True-Randomization#22]
Sometimes I want to go a little crazy, maybe the best sword in the game ends up with -10 attack, or a dagger has 500, you know?

**Comment by Lakifume** [comment]
In this case you may want to consider running the rando from source if you wish to make crazy changes. The main github page has a quick tutorial on how to build from source, but you can use python to directly run the rando from the .py files (either through a command or through a program such as PyCharm or Notepad++).

**Comment by MainMemory** [comment]
So you won't add an option like that?

**Comment by Lakifume** [comment]
Something as polarized as this I would not add in the main release no, but feel free to edit the code for yourself if you can run it from source.

**Comment by MainMemory** [comment]
It's just an option, it's not like anyone would have to use it...
