### ISSUE TITLE
Problem with launcher

### ISSUE THREAD

**Issue by GruncleD** [Lakifume/True-Randomization#25]
I haven't used the randomizer in awhile and am getting an error at launch.  I saw something in previous issues but was not sure what was the solution.  Can you please let me know how to fix this issue in simple terms?  See attached
![ROTNerror](https://user-images.githubusercontent.com/123063253/213393298-04d49636-be61-4474-b4fa-2ed0f74b7725.PNG)

**Comment by Lakifume** [comment]
Your computer is most likely blocking access to it. Get the zip file you previously extracted, right click on it, go to Properties, check the Unblock option, click Apply and extract again.

**Comment by GruncleD** [comment]
I did that and it still does the same thing
