### ISSUE TITLE
error while generating pak file

### ISSUE THREAD

**Issue by GruncleD** [Lakifume/True-Randomization#26]
![image_2023-01-24_090624107](https://user-images.githubusercontent.com/123063253/214330421-115f643e-57f3-433f-8404-9b9285a930f9.png)

**Comment by Lakifume** [comment]
Whoops that's an oversight from me, forgot to take in account users who don't own the IGA DLC. Will fix next update, use 2.8.2 in the meantime.

**Comment by Lakifume** [comment]
Actually removing the line
`"MI_N2013_face":                       "DLC\\DLC_0002\\Character\\N2013\\Material",`
from FileToPath.json should also fix it

**Comment by GruncleD** [comment]
how do i do that?

**Comment by Lakifume** [comment]
FileToPath.json is under the rando's Data folder, open it in any text editor, go to that line, remove it and save.

**Comment by GruncleD** [comment]
MI_N2013_face does not show in the FileToPath.json

**Comment by Lakifume** [comment]
Okay try the version I just released and tell me if it works for you

**Comment by GruncleD** [comment]
That fixed it
