### ISSUE TITLE
I think the new update broke rando again

### ISSUE THREAD

**Issue by SenseiLeRoof** [Lakifume/True-Randomization#32]
While attempting to generate rando (current release, game fully updated, do not yet have new DLC)...

Found 98688 game files (0 skipped) in 3926 folders at path "E:/Steam/steamapps/common/Bloodstained Ritual of the Night/BloodstainedRotN/Content/Paks"
Scanned game directory in 0.2 sec, 104445 allocs, 19.07 MBytes serialized in 36 calls.
Saving: E:/Mozzarella/Randomizers/BRotN True Random//Game/L10N/en/Core/StringTable/PBSystemStringTable.uasset
Saving: E:/Mozzarella/Randomizers/BRotN True Random//Game/L10N/en/Core/StringTable/PBSystemStringTable.uexp
Traceback (most recent call last):
  File "Randomizer.py", line 176, in run
  File "Randomizer.py", line 278, in process
  File "Manager.py", line 472, in apply_default_tweaks
IndexError: array index out of range

**Comment by Lakifume** [comment]
Yes 1.5 broke the rando however the damage is minimal. I am actively working on the next rando update to fix it and to handle the new DLC costumes.

**Comment by Lakifume** [comment]
Alright, the update is out. Let me know if other issues arise
