### ISSUE TITLE
Failed To Retrieve DLC Information from User Installation.  Proceeding without DLC.

### ISSUE THREAD

**Issue by F4T4LV0iD** [Lakifume/True-Randomization#33]
I get an error popup of "Failed To Retrieve DLC Information from User Installation.  Proceeding without DLC." when trying to generate a new seed.  I own all DLC but the soundtrack and just wondering what would have caused this error to pop up.  I'm not too bothered by it either way because I'm just glad it's working again, DLC or not.   It still finished the generation and is functioning fine otherwise.

**Comment by Lakifume** [comment]
Are you on Steam or GOG ?

**Comment by F4T4LV0iD** [comment]
> Are you on Steam or GOG ?

I am on Steam.

**Comment by Lakifume** [comment]
Okay what is your Steam user ID and friend code ?

**Comment by F4T4LV0iD** [comment]
> Okay what is your Steam user ID and friend code ?

steamcommunity.com/id/f4t4lv0id/
friend code is 5757169

**Comment by Lakifume** [comment]
Oh for your Steam ID I need the 17 digits number in C:\Program Files (x86)\Steam\config\loginusers.vdf
You can open it in Notepad

**Comment by F4T4LV0iD** [comment]
> Oh for your Steam ID I need the 17 digits number in C:\Program Files (x86)\Steam\config\loginusers.vdf You can open it in Notepad

76561197966022897

**Comment by Lakifume** [comment]
Okay thanks so that's not the issue. Can you confirm that the file C:\Program Files (x86)\Steam\userdata\5757169\config\localconfig.vdf exists ?

**Comment by F4T4LV0iD** [comment]
> Okay thanks so that's not the issue. Can you confirm that the file C:\Program Files (x86)\Steam\userdata\5757169\config\localconfig.vdf exists ?

It does, though it's on my D: drive if that matters

**Comment by Lakifume** [comment]
Hmm... can you show me the contents of the C:\Program Files (x86)\Steam\config\loginusers.vdf file ?

**Comment by F4T4LV0iD** [comment]
> Hmm... can you show me the contents of the C:\Program Files (x86)\Steam\config\loginusers.vdf file ?

![login](https://github.com/Lakifume/True-Randomization/assets/31555414/a41493cb-ab44-434d-b6e7-e183a5b4e0ce)

**Comment by Lakifume** [comment]
Okay I just released a hotfix for 3.0.1. Let me know if that fixes your issue.

**Comment by F4T4LV0iD** [comment]
> Okay I just released a hotfix for 3.0.1. Let me know if that fixes your issue.

I got the same popup when I clicked "Generate" after importing the assets.

**Comment by Lakifume** [comment]
Okay is the file loginusers.vdf not named exactly like this on your end ? Is there one uppercase letter in there perhaps ?

**Comment by F4T4LV0iD** [comment]
After I close the popup it still has a checkbox for "Ignore DLC" that I can enable and disable though where I can enter the seed name.

**Comment by F4T4LV0iD** [comment]
The exact path and filename for me is:
D:\Program Files (x86)\Steam\config\loginusers.vdf

**Comment by Lakifume** [comment]
Hmm... somehow it seems it is not finding that file despite the path being correct. I'll investigate later

**Comment by F4T4LV0iD** [comment]
I didn't get the error this time after I restarted Steam, and put the file in the same directory but in C: drive instead, I'm testing if it's restarting my Steam that fixed it, or making a copy on C drive instead

**Comment by F4T4LV0iD** [comment]
It must have been restarting Steam that did something.  I removed the file copy from C-drive and the error doesn't pop up now when generating a new seed.

**Comment by Lakifume** [comment]
Oh well I'm glad it ended up working, strange that you had to restart Steam

**Comment by F4T4LV0iD** [comment]
I don't think I've restarted Steam since purchasing the recent DLC if that had anything to do with it.
