### ISSUE TITLE
A crash on the ship

### ISSUE THREAD

**Issue by SenseiLeRoof** [Lakifume/True-Randomization#34]
Current randomizer version
Parameter string: 000000DB3AAF
Starting items: Teps Oceus, Gebel's Glasses, Double Jump, Solomon's Ring
Seed: 4266222665

UE4 crashes after the first cutscene when I enter Vepar's room. A dialog appears but it only says "Fatal error!"

**Comment by Lakifume** [comment]
I am unable to replicate your issue, do you have any other mods on ?

**Comment by SenseiLeRoof** [comment]
https://www.nexusmods.com/bloodstainedritualofthenight/mods/156
https://www.nexusmods.com/bloodstainedritualofthenight/mods/157
https://www.nexusmods.com/bloodstainedritualofthenight/mods/166
https://www.nexusmods.com/bloodstainedritualofthenight/mods/177
https://www.nexusmods.com/bloodstainedritualofthenight/mods/195

The only one I didn't have before is the last one. I can try without that and see if it fixes it.

**Comment by Lakifume** [comment]
Ah I knew it, boob physics is your problem. It is unstable during the Vepar and Dominique fight.

**Comment by SenseiLeRoof** [comment]
Weird, it was never a problem before. And the mod in question _specifically_ only affects Miriam.
