### ISSUE TITLE
Craftwork softlock

### ISSUE THREAD

**Issue by SenseiLeRoof** [Lakifume/True-Randomization#35]
Same settings as in issue #34 

After burning the crap out of Craftwork with Insatiable, he died and gave me a Teps Oceus, but his corpse refused to disappear and the doors stayed shut, leaving me trapped in the room.

**Comment by Lakifume** [comment]
Did you already have Tep Oceus before he gave it to you ? Does the debug window show any errors ?

**Comment by Lakifume** [comment]
Try pressing F2 after defeating him to open the doors.

**Comment by SenseiLeRoof** [comment]
TO was one of my starting items. Nothing strange in the debug window.
F2 did the trick.

**Comment by Lakifume** [comment]
Okay yeah my current script for preventing the boss softlocks only detects the shard if it's one you don't already have. In the opposite case press F2 to end the boss manually. Same goes for Glutton Train and IGA.
