### ISSUE TITLE
More problems with the new DLC

### ISSUE THREAD

**Issue by SenseiLeRoof** [Lakifume/True-Randomization#36]
1. The first time I try to start with a new-DLC item, the randomizer fails with error "Spoiler". But only the first time. I don't know if it's per item or per DLC.
2. It won't give me the Succubus items. Rando will run properly with no errors but on new game start it doesn't give me the items. I've tried fresh reinstall of the game and restarting Steam, with no luck. (I tried once with them and Double Jump, and only got Double Jump.)

**Comment by SenseiLeRoof** [comment]
All it said was "spoiler". And I bought the bundle so I have all the new cosmetics.

**Comment by SenseiLeRoof** [comment]
Okay, we can knock off #2. The problem was with Steam not automatically downloading newly-bought DLC, so I was working with an import that didn't have the data.

**Comment by Lakifume** [comment]
Not sure about the spoiler error, I'm guessing it happens if the spoiler folder doesn't already exist ?
