### ISSUE TITLE
Non-item item obtained

### ISSUE THREAD

**Issue by SenseiLeRoof** [Lakifume/True-Randomization#5]
Version 2.2.9, so it may be fixed already, but just in case
![Bloody](https://user-images.githubusercontent.com/29762285/133910131-3fe121e0-df31-48a2-9995-3037e65a1433.png)
:

The indicated item was a monster drop, I think from a Seama. It doesn't show up in the item archives at all.

**Comment by Lakifume** [comment]
I have actually seen this unknown item with the Crow of Creation icon appear once in vanilla rando before, as one of the quest rewards. So I'm gonna have to call this a vanilla glitch. Just to check, after you defeat Bathin and get the actual Crown of Creation in the shop, does its name display correctly ?

**Comment by SenseiLeRoof** [comment]
I should've known I was too eager to give the new update a run. That save's been deleted. I was only into the Cathedral, nowhere near Bathin, le sigh.

If it happened in vanilla, we can close this anyway.
