### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [Lakifume/True-Randomization#8]
No idea why..

![image](https://user-images.githubusercontent.com/10475153/147844660-684a72c4-5843-4a52-8a8d-4c0bf8111b0c.png)

**Comment by Lakifume** [comment]
Oh your computer must be configured in a language that doesn't support certain characters in the json files. Well you can fix your current issue by going opening Serializer\Json\PBSystemStringTable.json in notepad, scroll down to the "SYS_MSG_Saving" entry and replace the single character "…" by 3 regular dots.

**Comment by ParanoiaIsGreat** [comment]
Is this right? Didn't work. :(
![image](https://user-images.githubusercontent.com/10475153/147853164-49bbdb3c-2cd1-4b0b-bd8e-1038c0db6f3c.png)

**Comment by Lakifume** [comment]
It did work, it's just that there are apparently more characters that cause issues. The error gives you the position of said character ("in position 11646") so keep replacing those until it works. Currently the next one is a weird "＋" that can be replaced with a regular +.

**Comment by ParanoiaIsGreat** [comment]
Ok, I'll try more. Thx!

**Comment by Lakifume** [comment]
Once you're done you can report to me all the characters that needed to be changed so that I can do it on my end as well and put that in the next update download by default.

**Comment by ParanoiaIsGreat** [comment]
Of course, but how do I replace a ↓ down arrow?

**Comment by ParanoiaIsGreat** [comment]
After I changed ↓ to Down Button, it seems works. 
Can you check it? It's 0:13 now in my time zone, need to sleep.
Oh my win10 language is Chinese btw. I don't know if it works for a different language system.
![image](https://user-images.githubusercontent.com/10475153/147854779-d1f30f0d-3398-4269-b446-97caac8421d0.png)
[True.Randomization.zip](https://github.com/Lakifume/True-Randomization/files/7797890/True.Randomization.zip)

**Comment by Lakifume** [comment]
Yep that's good, thanks
